import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/widgets/Navbar";


export const metadata: Metadata = {
  title: "K",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >        
        {children}
      </body>
    </html>
  );
}
